[server]
# WebSocket server configuration
host = "127.0.0.1"
port = 8080
max_connections = 1000
heartbeat_interval = 30

# TLS configuration for encrypted communication
tls_enabled = false
tls_cert_path = ""
tls_key_path = ""

# Performance tuning
read_buffer_size = 8192
write_buffer_size = 8192
max_message_size = 1048576  # 1MB

[auth]
# Authentication configuration
token_secret = "your-secret-key-change-in-production"
token_expiry = 3600 

[firestore]
# Firestore integration configuration
project_id = "your-project-id"
credentials_path = ""
collection_prefix = "signal_sessions" 