# Signal Management Service Configuration
# This file contains all configuration options for the signal management service

[server]
# WebSocket server configuration
host = "127.0.0.1"
port = 8080
max_connections = 1000
heartbeat_interval = 30

# TLS configuration for encrypted communication
tls_enabled = false
tls_cert_path = ""
tls_key_path = ""

# Performance tuning
read_buffer_size = 8192
write_buffer_size = 8192
max_message_size = 1048576  # 1MB

[firestore]
# Firestore integration configuration
project_id = "your-project-id"
credentials_path = ""
collection_prefix = "signal_sessions"

[auth]
# Authentication configuration
token_secret = "your-secret-key-change-in-production"
token_expiry = 3600
auth_method = "token"  # Options: "token", "api_key", "firestore"

# API key configuration (if using API key auth)
api_keys = [
    "test_client_1:test_token_1",
    "test_client_2:test_token_2"
]

[logging]
# Logging configuration
level = "info"
format = "json"
file_path = ""  # Set to path for file logging
console_output = true

# Log rotation settings
max_file_size = 10485760  # 10MB
max_files = 5

[metrics]
# Metrics and monitoring configuration
enabled = true
port = 9090
host = "127.0.0.1"

# Metrics collection intervals
connection_stats_interval = 60
message_stats_interval = 30

[session]
# Session management configuration
session_timeout = 3600
cleanup_interval = 300
max_sessions_per_client = 1

[security]
# Security configuration
rate_limit_enabled = true
max_messages_per_minute = 1000
max_connections_per_ip = 10

# CORS settings for WebSocket connections
allowed_origins = ["*"] 

[gcp]
credentials_path = "/home/keith/Downloads/keahi-ambient-agent-service-d9c5c0e3f93a.json"
project_id = "your-gcp-project-id"
pubsub_topic = "signal-manager-events"
pubsub_subscription = "signal-manager-events-subscription"
region = "europe-west2" 