[server]
host = "127.0.0.1"
port = 8080
max_connections = 1000
heartbeat_interval = 30
tls_enabled = false
tls_cert_path = ""
tls_key_path = ""
read_buffer_size = 8192
write_buffer_size = 8192
max_message_size = 1048576

[firestore]
project_id = "your-project-id"
credentials_path = ""
database_name = "signal-manager-service-db"
auth_method = "service_account"
collection_name = "clients"
region = "us-central1"

[auth]
token_secret = "your-secret-key-change-in-production"
token_expiry = 3600
auth_method = "token"
api_keys = ["test_client_1:test_token_1", "test_client_2:test_token_2"]

[logging]
level = "info"
format = "json"
console_output = true
max_file_size = 10485760
max_files = 5

[metrics]
enabled = true
port = 9090
host = "127.0.0.1"
connection_stats_interval = 60
message_stats_interval = 30

[session]
session_timeout = 3600
cleanup_interval = 300
max_sessions_per_client = 1

[security]
rate_limit_enabled = true
max_messages_per_minute = 100
max_connections_per_ip = 10
allowed_origins = ["*"]

[gcp]
credentials_path = ""
project_id = "your-project-id"
region = "us-central1"

[cloudflare]
app_id = "your-cloudflare-app-id"
app_secret = "your-cloudflare-app-secret"
base_url = "https://api.cloudflare.com/client/v4"
stun_url = "stun:stun.cloudflare.com:3478" 